(ns clj-globetrotter.world)

(def world [{:source :alaska :target :boston :time 10 :price 410 :method :plane}
            {:source :alaska :target :costa-rica :time 14 :price 574 :method :plane}
            {:source :alaska :target :hawaii :time 93 :price 119 :method :ferry}
            {:source :alaska :target :irkutsk :time 11 :price 438 :method :plane}
            {:source :alaska :target :san-francisco :time 6 :price 267 :method :plane}
            {:source :alaska :target :san-francisco :time 46 :price 51 :method :bus}
            {:source :alaska :target :san-francisco :time 65 :price 89 :method :ferry}
            {:source :alaska :target :shanghai :time 146 :price 174 :method :ferry}
            {:source :alaska :target :the-wild-west :time 7 :price 300 :method :plane}
            {:source :amazonas :target :costa-rica :time 43 :price 47 :method :bus}
            {:source :amazonas :target :el-mundo-maya :time 83 :price 108 :method :ferry}
            {:source :amazonas :target :galapagos :time 68 :price 92 :method :ferry}
            {:source :amazonas :target :havana :time 76 :price 101 :method :ferry}
            {:source :amsterdam :target :berlin :time 4 :price 40 :method :train}
            {:source :amsterdam :target :boston :time 117 :price 143 :method :ferry}
            {:source :amsterdam :target :budapest :time 2 :price 130 :method :plane}
            {:source :amsterdam :target :costa-rica :time 190 :price 220 :method :ferry}
            {:source :amsterdam :target :ireland :time 19 :price 41 :method :ferry}
            {:source :amsterdam :target :london :time 4 :price 38 :method :train}
            {:source :amsterdam :target :london :time 6 :price 17 :method :bus}
            {:source :amsterdam :target :paris :time 4 :price 38 :method :train}
            {:source :amsterdam :target :paris :time 6 :price 17 :method :bus}
            {:source :amsterdam :target :samarkand :time 9 :price 370 :method :plane}
            {:source :amsterdam :target :st-petersburg :time 3 :price 180 :method :plane}
            {:source :amsterdam :target :washington :time 11 :price 465 :method :plane}
            {:source :athens :target :bangkok :time 15 :price 595 :method :plane}
            {:source :athens :target :berlin :time 15 :price 76 :method :train}
            {:source :athens :target :boston :time 156 :price 185 :method :ferry}
            {:source :athens :target :budapest :time 9 :price 57 :method :train}
            {:source :athens :target :ireland :time 5 :price 249 :method :plane}
            {:source :athens :target :lhasa :time 11 :price 461 :method :plane}
            {:source :athens :target :london :time 4 :price 219 :method :plane}
            {:source :athens :target :london :time 21 :price 93 :method :train}
            {:source :athens :target :paris :time 17 :price 83 :method :train}
            {:source :athens :target :paris :time 30 :price 37 :method :bus}
            {:source :athens :target :st-petersburg :time 23 :price 101 :method :train}
            {:source :athens :target :yemen :time 74 :price 98 :method :ferry}
            {:source :bangkok :target :athens :time 15 :price 595 :method :plane}
            {:source :bangkok :target :irkutsk :time 41 :price 158 :method :train}
            {:source :bangkok :target :london :time 18 :price 695 :method :plane}
            {:source :bangkok :target :maldives :time 64 :price 88 :method :ferry}
            {:source :bangkok :target :manila :time 52 :price 75 :method :ferry}
            {:source :bangkok :target :new-delhi :time 25 :price 109 :method :train}
            {:source :bangkok :target :shanghai :time 26 :price 110 :method :train}
            {:source :bangkok :target :sydney :time 14 :price 541 :method :plane}
            {:source :bangkok :target :sydney :time 152 :price 180 :method :ferry}
            {:source :bangkok :target :thimphu :time 30 :price 37 :method :bus}
            {:source :bangkok :target :tokyo :time 9 :price 376 :method :plane}
            {:source :bangkok :target :yemen :time 118 :price 144 :method :ferry}
            {:source :berlin :target :athens :time 15 :price 76 :method :train}
            {:source :berlin :target :budapest :time 6 :price 46 :method :train}
            {:source :berlin :target :costa-rica :time 18 :price 691 :method :plane}
            {:source :berlin :target :iceland :time 4 :price 206 :method :plane}
            {:source :berlin :target :london :time 7 :price 51 :method :train}
            {:source :berlin :target :new-delhi :time 11 :price 459 :method :plane}
            {:source :berlin :target :paris :time 7 :price 49 :method :train}
            {:source :berlin :target :st-petersburg :time 13 :price 67 :method :train}
            {:source :berlin :target :tanzania :time 13 :price 505 :method :plane}
            {:source :boston :target :alaska :time 10 :price 410 :method :plane}
            {:source :boston :target :amsterdam :time 117 :price 143 :method :ferry}
            {:source :boston :target :athens :time 156 :price 185 :method :ferry}
            {:source :boston :target :havana :time 4 :price 211 :method :plane}
            {:source :boston :target :ireland :time 98 :price 123 :method :ferry}
            {:source :boston :target :montreal :time 1 :price 85 :method :plane}
            {:source :boston :target :montreal :time 3 :price 36 :method :train}
            {:source :boston :target :san-francisco :time 36 :price 144 :method :train}
            {:source :boston :target :the-wild-west :time 24 :price 104 :method :train}
            {:source :boston :target :washington :time 1 :price 97 :method :plane}
            {:source :boston :target :washington :time 5 :price 41 :method :train}
            {:source :boston :target :washington :time 8 :price 18 :method :bus}
            {:source :budapest :target :amsterdam :time 2 :price 130 :method :plane}
            {:source :budapest :target :athens :time 9 :price 57 :method :train}
            {:source :budapest :target :berlin :time 6 :price 46 :method :train}
            {:source :budapest :target :ireland :time 4 :price 191 :method :plane}
            {:source :budapest :target :irkutsk :time 10 :price 422 :method :plane}
            {:source :budapest :target :manila :time 18 :price 697 :method :plane}
            {:source :budapest :target :paris :time 10 :price 60 :method :train}
            {:source :budapest :target :samarkand :time 33 :price 134 :method :train}
            {:source :budapest :target :st-petersburg :time 15 :price 75 :method :train}
            {:source :budapest :target :st-petersburg :time 26 :price 33 :method :bus}
            {:source :budapest :target :yemen :time 67 :price 68 :method :bus}
            {:source :costa-rica :target :alaska :time 14 :price 574 :method :plane}
            {:source :costa-rica :target :amazonas :time 43 :price 47 :method :bus}
            {:source :costa-rica :target :amsterdam :time 190 :price 220 :method :ferry}
            {:source :costa-rica :target :berlin :time 18 :price 691 :method :plane}
            {:source :costa-rica :target :el-mundo-maya :time 21 :price 29 :method :bus}
            {:source :costa-rica :target :el-mundo-maya :time 29 :price 51 :method :ferry}
            {:source :costa-rica :target :galapagos :time 23 :price 44 :method :ferry}
            {:source :costa-rica :target :havana :time 3 :price 171 :method :plane}
            {:source :costa-rica :target :havana :time 34 :price 57 :method :ferry}
            {:source :costa-rica :target :manila :time 327 :price 363 :method :ferry}
            {:source :costa-rica :target :sahara :time 17 :price 658 :method :plane}
            {:source :costa-rica :target :san-francisco :time 43 :price 167 :method :train}
            {:source :costa-rica :target :the-wild-west :time 36 :price 144 :method :train}
            {:source :costa-rica :target :tokyo :time 24 :price 918 :method :plane}
            {:source :el-mundo-maya :target :amazonas :time 83 :price 108 :method :ferry}
            {:source :el-mundo-maya :target :costa-rica :time 21 :price 29 :method :bus}
            {:source :el-mundo-maya :target :costa-rica :time 29 :price 51 :method :ferry}
            {:source :el-mundo-maya :target :havana :time 16 :price 38 :method :ferry}
            {:source :el-mundo-maya :target :san-francisco :time 7 :price 306 :method :plane}
            {:source :el-mundo-maya :target :shanghai :time 25 :price 941 :method :plane}
            {:source :el-mundo-maya :target :the-wild-west :time 5 :price 245 :method :plane}
            {:source :el-mundo-maya :target :the-wild-west :time 41 :price 46 :method :bus}
            {:source :galapagos :target :amazonas :time 68 :price 92 :method :ferry}
            {:source :galapagos :target :costa-rica :time 23 :price 44 :method :ferry}
            {:source :galapagos :target :hawaii :time 151 :price 179 :method :ferry}
            {:source :galapagos :target :new-zealand :time 209 :price 240 :method :ferry}
            {:source :galapagos :target :tokyo :time 275 :price 310 :method :ferry}
            {:source :havana :target :amazonas :time 76 :price 101 :method :ferry}
            {:source :havana :target :boston :time 4 :price 211 :method :plane}
            {:source :havana :target :costa-rica :time 3 :price 171 :method :plane}
            {:source :havana :target :costa-rica :time 34 :price 57 :method :ferry}
            {:source :havana :target :el-mundo-maya :time 16 :price 38 :method :ferry}
            {:source :havana :target :hawaii :time 14 :price 543 :method :plane}
            {:source :havana :target :london :time 14 :price 542 :method :plane}
            {:source :havana :target :montreal :time 52 :price 75 :method :ferry}
            {:source :havana :target :washington :time 3 :price 181 :method :plane}
            {:source :hawaii :target :alaska :time 93 :price 119 :method :ferry}
            {:source :hawaii :target :galapagos :time 151 :price 179 :method :ferry}
            {:source :hawaii :target :havana :time 14 :price 543 :method :plane}
            {:source :hawaii :target :montreal :time 14 :price 564 :method :plane}
            {:source :hawaii :target :san-francisco :time 7 :price 301 :method :plane}
            {:source :hawaii :target :san-francisco :time 76 :price 100 :method :ferry}
            {:source :hawaii :target :shanghai :time 15 :price 591 :method :plane}
            {:source :hawaii :target :sydney :time 172 :price 201 :method :ferry}
            {:source :hawaii :target :tokyo :time 133 :price 160 :method :ferry}
            {:source :iceland :target :berlin :time 4 :price 206 :method :plane}
            {:source :iceland :target :ireland :time 30 :price 52 :method :ferry}
            {:source :iceland :target :london :time 3 :price 170 :method :plane}
            {:source :iceland :target :montreal :time 7 :price 319 :method :plane}
            {:source :iceland :target :montreal :time 81 :price 106 :method :ferry}
            {:source :iceland :target :paris :time 4 :price 201 :method :plane}
            {:source :ireland :target :amsterdam :time 19 :price 41 :method :ferry}
            {:source :ireland :target :athens :time 5 :price 249 :method :plane}
            {:source :ireland :target :boston :time 98 :price 123 :method :ferry}
            {:source :ireland :target :budapest :time 4 :price 191 :method :plane}
            {:source :ireland :target :iceland :time 30 :price 52 :method :ferry}
            {:source :ireland :target :london :time 1 :price 97 :method :plane}
            {:source :ireland :target :paris :time 2 :price 118 :method :plane}
            {:source :ireland :target :st-petersburg :time 4 :price 221 :method :plane}
            {:source :irkutsk :target :alaska :time 11 :price 438 :method :plane}
            {:source :irkutsk :target :bangkok :time 41 :price 158 :method :train}
            {:source :irkutsk :target :budapest :time 10 :price 422 :method :plane}
            {:source :irkutsk :target :samarkand :time 6 :price 258 :method :plane}
            {:source :irkutsk :target :shanghai :time 28 :price 117 :method :train}
            {:source :irkutsk :target :st-petersburg :time 61 :price 62 :method :bus}
            {:source :lhasa :target :athens :time 11 :price 461 :method :plane}
            {:source :lhasa :target :mt-everest :time 6 :price 16 :method :bus}
            {:source :lhasa :target :new-delhi :time 3 :price 161 :method :plane}
            {:source :london :target :amsterdam :time 4 :price 38 :method :train}
            {:source :london :target :amsterdam :time 6 :price 17 :method :bus}
            {:source :london :target :athens :time 4 :price 219 :method :plane}
            {:source :london :target :athens :time 21 :price 93 :method :train}
            {:source :london :target :bangkok :time 18 :price 695 :method :plane}
            {:source :london :target :berlin :time 7 :price 51 :method :train}
            {:source :london :target :havana :time 14 :price 542 :method :plane}
            {:source :london :target :iceland :time 3 :price 170 :method :plane}
            {:source :london :target :ireland :time 1 :price 97 :method :plane}
            {:source :london :target :paris :time 4 :price 40 :method :train}
            {:source :maldives :target :bangkok :time 64 :price 88 :method :ferry}
            {:source :maldives :target :tanzania :time 8 :price 358 :method :plane}
            {:source :maldives :target :yemen :time 60 :price 84 :method :ferry}
            {:source :maldives :target :zanzibar :time 74 :price 98 :method :ferry}
            {:source :manila :target :bangkok :time 52 :price 75 :method :ferry}
            {:source :manila :target :budapest :time 18 :price 697 :method :plane}
            {:source :manila :target :costa-rica :time 327 :price 363 :method :ferry}
            {:source :manila :target :new-zealand :time 15 :price 594 :method :plane}
            {:source :manila :target :shanghai :time 30 :price 52 :method :ferry}
            {:source :manila :target :sydney :time 132 :price 159 :method :ferry}
            {:source :montreal :target :boston :time 1 :price 85 :method :plane}
            {:source :montreal :target :boston :time 3 :price 36 :method :train}
            {:source :montreal :target :havana :time 52 :price 75 :method :ferry}
            {:source :montreal :target :hawaii :time 14 :price 564 :method :plane}
            {:source :montreal :target :iceland :time 7 :price 319 :method :plane}
            {:source :montreal :target :iceland :time 81 :price 106 :method :ferry}
            {:source :montreal :target :san-francisco :time 35 :price 139 :method :train}
            {:source :montreal :target :the-wild-west :time 5 :price 234 :method :plane}
            {:source :montreal :target :the-wild-west :time 23 :price 100 :method :train}
            {:source :montreal :target :washington :time 1 :price 109 :method :plane}
            {:source :montreal :target :washington :time 6 :price 47 :method :train}
            {:source :mt-everest :target :lhasa :time 6 :price 16 :method :bus}
            {:source :mt-everest :target :thimphu :time 6 :price 17 :method :bus}
            {:source :new-delhi :target :bangkok :time 25 :price 109 :method :train}
            {:source :new-delhi :target :berlin :time 11 :price 459 :method :plane}
            {:source :new-delhi :target :lhasa :time 3 :price 161 :method :plane}
            {:source :new-delhi :target :sahara :time 14 :price 550 :method :plane}
            {:source :new-delhi :target :samarkand :time 17 :price 81 :method :train}
            {:source :new-delhi :target :samarkand :time 29 :price 36 :method :bus}
            {:source :new-delhi :target :yemen :time 6 :price 271 :method :plane}
            {:source :new-zealand :target :galapagos :time 209 :price 240 :method :ferry}
            {:source :new-zealand :target :manila :time 15 :price 594 :method :plane}
            {:source :new-zealand :target :sahara :time 33 :price 1210 :method :plane}
            {:source :new-zealand :target :sydney :time 4 :price 204 :method :plane}
            {:source :new-zealand :target :sydney :time 45 :price 68 :method :ferry}
            {:source :new-zealand :target :zanzibar :time 260 :price 293 :method :ferry}
            {:source :paris :target :amsterdam :time 4 :price 38 :method :train}
            {:source :paris :target :amsterdam :time 6 :price 17 :method :bus}
            {:source :paris :target :athens :time 17 :price 83 :method :train}
            {:source :paris :target :athens :time 30 :price 37 :method :bus}
            {:source :paris :target :berlin :time 7 :price 49 :method :train}
            {:source :paris :target :budapest :time 10 :price 60 :method :train}
            {:source :paris :target :iceland :time 4 :price 201 :method :plane}
            {:source :paris :target :ireland :time 2 :price 118 :method :plane}
            {:source :paris :target :london :time 4 :price 40 :method :train}
            {:source :paris :target :tokyo :time 18 :price 684 :method :plane}
            {:source :paris :target :washington :time 11 :price 458 :method :plane}
            {:source :paris :target :yemen :time 10 :price 427 :method :plane}
            {:source :sahara :target :costa-rica :time 17 :price 658 :method :plane}
            {:source :sahara :target :new-delhi :time 14 :price 550 :method :plane}
            {:source :sahara :target :new-zealand :time 33 :price 1210 :method :plane}
            {:source :sahara :target :samarkand :time 93 :price 89 :method :bus}
            {:source :sahara :target :tanzania :time 68 :price 69 :method :bus}
            {:source :samarkand :target :amsterdam :time 9 :price 370 :method :plane}
            {:source :samarkand :target :budapest :time 33 :price 134 :method :train}
            {:source :samarkand :target :irkutsk :time 6 :price 258 :method :plane}
            {:source :samarkand :target :new-delhi :time 17 :price 81 :method :train}
            {:source :samarkand :target :new-delhi :time 29 :price 36 :method :bus}
            {:source :samarkand :target :sahara :time 93 :price 89 :method :bus}
            {:source :samarkand :target :shanghai :time 10 :price 400 :method :plane}
            {:source :samarkand :target :st-petersburg :time 30 :price 123 :method :train}
            {:source :san-francisco :target :alaska :time 6 :price 267 :method :plane}
            {:source :san-francisco :target :alaska :time 46 :price 51 :method :bus}
            {:source :san-francisco :target :alaska :time 65 :price 89 :method :ferry}
            {:source :san-francisco :target :boston :time 36 :price 144 :method :train}
            {:source :san-francisco :target :costa-rica :time 43 :price 167 :method :train}
            {:source :san-francisco :target :el-mundo-maya :time 7 :price 306 :method :plane}
            {:source :san-francisco :target :hawaii :time 7 :price 301 :method :plane}
            {:source :san-francisco :target :hawaii :time 76 :price 100 :method :ferry}
            {:source :san-francisco :target :montreal :time 35 :price 139 :method :train}
            {:source :san-francisco :target :shanghai :time 204 :price 235 :method :ferry}
            {:source :san-francisco :target :the-wild-west :time 3 :price 156 :method :plane}
            {:source :san-francisco :target :the-wild-west :time 12 :price 66 :method :train}
            {:source :san-francisco :target :tokyo :time 15 :price 590 :method :plane}
            {:source :san-francisco :target :tokyo :time 167 :price 196 :method :ferry}
            {:source :san-francisco :target :washington :time 33 :price 134 :method :train}
            {:source :san-francisco :target :washington :time 57 :price 59 :method :bus}
            {:source :shanghai :target :alaska :time 146 :price 174 :method :ferry}
            {:source :shanghai :target :bangkok :time 26 :price 110 :method :train}
            {:source :shanghai :target :el-mundo-maya :time 25 :price 941 :method :plane}
            {:source :shanghai :target :hawaii :time 15 :price 591 :method :plane}
            {:source :shanghai :target :irkutsk :time 28 :price 117 :method :train}
            {:source :shanghai :target :manila :time 30 :price 52 :method :ferry}
            {:source :shanghai :target :samarkand :time 10 :price 400 :method :plane}
            {:source :shanghai :target :san-francisco :time 204 :price 235 :method :ferry}
            {:source :shanghai :target :the-wild-west :time 20 :price 759 :method :plane}
            {:source :shanghai :target :tokyo :time 37 :price 60 :method :ferry}
            {:source :st-petersburg :target :amsterdam :time 3 :price 180 :method :plane}
            {:source :st-petersburg :target :athens :time 23 :price 101 :method :train}
            {:source :st-petersburg :target :berlin :time 13 :price 67 :method :train}
            {:source :st-petersburg :target :budapest :time 15 :price 75 :method :train}
            {:source :st-petersburg :target :budapest :time 26 :price 33 :method :bus}
            {:source :st-petersburg :target :ireland :time 4 :price 221 :method :plane}
            {:source :st-petersburg :target :irkutsk :time 61 :price 62 :method :bus}
            {:source :st-petersburg :target :samarkand :time 30 :price 123 :method :train}
            {:source :st-petersburg :target :sydney :time 28 :price 1039 :method :plane}
            {:source :sydney :target :bangkok :time 14 :price 541 :method :plane}
            {:source :sydney :target :bangkok :time 152 :price 180 :method :ferry}
            {:source :sydney :target :hawaii :time 172 :price 201 :method :ferry}
            {:source :sydney :target :manila :time 132 :price 159 :method :ferry}
            {:source :sydney :target :new-zealand :time 4 :price 204 :method :plane}
            {:source :sydney :target :new-zealand :time 45 :price 68 :method :ferry}
            {:source :sydney :target :st-petersburg :time 28 :price 1039 :method :plane}
            {:source :sydney :target :tokyo :time 15 :price 590 :method :plane}
            {:source :sydney :target :zanzibar :time 20 :price 773 :method :plane}
            {:source :tanzania :target :berlin :time 13 :price 505 :method :plane}
            {:source :tanzania :target :maldives :time 8 :price 358 :method :plane}
            {:source :tanzania :target :sahara :time 68 :price 69 :method :bus}
            {:source :tanzania :target :zanzibar :time 2 :price 135 :method :plane}
            {:source :the-wild-west :target :alaska :time 7 :price 300 :method :plane}
            {:source :the-wild-west :target :boston :time 24 :price 104 :method :train}
            {:source :the-wild-west :target :costa-rica :time 36 :price 144 :method :train}
            {:source :the-wild-west :target :el-mundo-maya :time 5 :price 245 :method :plane}
            {:source :the-wild-west :target :el-mundo-maya :time 41 :price 46 :method :bus}
            {:source :the-wild-west :target :montreal :time 5 :price 234 :method :plane}
            {:source :the-wild-west :target :montreal :time 23 :price 100 :method :train}
            {:source :the-wild-west :target :san-francisco :time 3 :price 156 :method :plane}
            {:source :the-wild-west :target :san-francisco :time 12 :price 66 :method :train}
            {:source :the-wild-west :target :shanghai :time 20 :price 759 :method :plane}
            {:source :the-wild-west :target :washington :time 21 :price 95 :method :train}
            {:source :thimphu :target :bangkok :time 30 :price 37 :method :bus}
            {:source :thimphu :target :mt-everest :time 6 :price 17 :method :bus}
            {:source :tokyo :target :bangkok :time 9 :price 376 :method :plane}
            {:source :tokyo :target :costa-rica :time 24 :price 918 :method :plane}
            {:source :tokyo :target :hawaii :time 133 :price 160 :method :ferry}
            {:source :tokyo :target :paris :time 18 :price 684 :method :plane}
            {:source :tokyo :target :san-francisco :time 15 :price 590 :method :plane}
            {:source :tokyo :target :san-francisco :time 167 :price 196 :method :ferry}
            {:source :tokyo :target :shanghai :time 37 :price 60 :method :ferry}
            {:source :tokyo :target :sydney :time 15 :price 590 :method :plane}
            {:source :washington :target :amsterdam :time 11 :price 465 :method :plane}
            {:source :washington :target :boston :time 1 :price 97 :method :plane}
            {:source :washington :target :boston :time 5 :price 41 :method :train}
            {:source :washington :target :boston :time 8 :price 18 :method :bus}
            {:source :washington :target :havana :time 3 :price 181 :method :plane}
            {:source :washington :target :montreal :time 1 :price 109 :method :plane}
            {:source :washington :target :montreal :time 6 :price 47 :method :train}
            {:source :washington :target :paris :time 11 :price 458 :method :plane}
            {:source :washington :target :san-francisco :time 33 :price 134 :method :train}
            {:source :washington :target :san-francisco :time 57 :price 59 :method :bus}
            {:source :washington :target :the-wild-west :time 21 :price 95 :method :train}
            {:source :yemen :target :athens :time 74 :price 98 :method :ferry}
            {:source :yemen :target :bangkok :time 118 :price 144 :method :ferry}
            {:source :yemen :target :budapest :time 67 :price 68 :method :bus}
            {:source :yemen :target :maldives :time 60 :price 84 :method :ferry}
            {:source :yemen :target :new-delhi :time 6 :price 271 :method :plane}
            {:source :yemen :target :paris :time 10 :price 427 :method :plane}
            {:source :yemen :target :zanzibar :time 53 :price 77 :method :ferry}
            {:source :zanzibar :target :maldives :time 74 :price 98 :method :ferry}
            {:source :zanzibar :target :new-zealand :time 260 :price 293 :method :ferry}
            {:source :zanzibar :target :sydney :time 20 :price 773 :method :plane}
            {:source :zanzibar :target :tanzania :time 2 :price 135 :method :plane}
            {:source :zanzibar :target :yemen :time 53 :price 77 :method :ferry}])
